name: "Example"
description: "Receives file and generates output"
inputs:
  file-path:
    description: "Path to test script"
    required: true
    default: "test-file.js"
outputs:
  results-file:
    description: "Path to results file"
runs:
  using: "node20"
  main: "index.js"
