name: Reusable Workflow
run-name: A Workflow that is Reusable
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
    outputs:
      firstword:
        description: "The first word"
        value: ${{ jobs.example-job.outputs.output1 }}

jobs:
  example-job:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.step1.outputs.firstword}}
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
