name: Reusable Workflow
run-name: A Workflow that is Reusable
on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Path
        run: echo "config path /:/ ${{inputs.config-path}}"
