name: Using variables in your workflows
run-name: ${{github.action_repository}} is where this is being run
on:
  push:
    branches:
      - essential_features

jobs:
  variable_job:
    runs-on: ubuntu-latest
    steps:
      - name: Creating environment variables
        run: node client.js
        env:
          TEST: testing
