name: Using variables in your workflows
run-name: Testing to see how variables work
on:
  push:
    branches:
      - essential_features

jobs:
  variable_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Creating environment variables"
        run: |
          echo "${{github.workspace}} + ${{github.actor}}"
          node client.js
        env:
          TEST: testing
